kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apirator
subjects:
  - kind: ServiceAccount
    name: apirator
roleRef:
  kind: Role
  name: apirator
  apiGroup: rbac.authorization.k8s.io